# Generated by Django 2.0 on 2019-01-13 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=300)),
                ('completed', models.BooleanField(default=False)),
                ('Deadline', models.DateTimeField(default=datetime.datetime(2019, 4, 13, 3, 46, 8, 807016))),
            ],
        ),
    ]
